version: 2

jobs:
  frontend-build-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Front-End Build
          command: |
            npm run build

      - run:
          name: Front-End Unit Tests
          command: |
            npm run test

      - run:
          name: Istanbul coverage
          command: |
            npm run coverage

      - run:
          name: Install xvfb
          command: |
            npm run install:xvfb

      - run:
          name: Front-End e2e Tests
          command: |
            npm run test:e2e

      - run:
          name: Istanbul coverage badges
          command: |
            npm run make-badges:ci

workflows:
  version: 2
  frontend-build-test-workflow:
    jobs:
      - frontend-build-test
